sonar.projectKey=GC-Bank
sonar.projectName=GC-Bank
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.libraries=target/classes
sonar.organization=jinal1112
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml