# k8s/keyvault/secret-provider-class.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: bankapp-azure-kv
  namespace: bankapp
spec:
  provider: azure
  secretObjects:
    - secretName: bankapp-secret
      type: Opaque
      data:
        - objectName: DB-USERNAME
          key: DB_USERNAME
        - objectName: DB-PASSWORD
          key: DB_PASSWORD
    - secretName: mysql-secret
      type: Opaque
      data:
        - objectName: MYSQL-ROOT-PASSWORD
          key: MYSQL_ROOT_PASSWORD
        - objectName: DB-USERNAME
          key: DB_USERNAME
        - objectName: DB-PASSWORD
          key: DB_PASSWORD
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: "bankapp-kv-jinal-1112"
    tenantID: "b4d9976d-c095-4323-9940-00d8e8f6df90"
    objects: |
      array:
        - |
          objectName: DB-USERNAME
          objectType: secret
        - |
          objectName: DB-PASSWORD
          objectType: secret
        - |
          objectName: MYSQL-ROOT-PASSWORD
          objectType: secret