apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: webapps
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Test@123"
  MYSQL_DATABASE: "bankappdb"
  DB_USERNAME: "root"
  DB_PASSWORD: "Test@123"