apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999     
        runAsGroup: 999    
        fsGroup: 999       
        seccompProfile:
          type: RuntimeDefault   
      containers:
        - name: mysql
          image: mysql:8
          securityContext:
            runAsUser: 999   
            runAsGroup: 999 
            allowPrivilegeEscalation: false   
            readOnlyRootFilesystem: true      
            capabilities:
              drop:
                - ALL                         
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_NAME
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
         - name: secrets-store-inline
           csi:
             driver: secrets-store.csi.k8s.io
             readOnly: true
             volumeAttributes:
                secretProviderClass: "bankapp-azure-kv"
             nodePublishSecretRef:
                name: secrets-store-creds
