apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  DB_USERNAME: {{ .Values.bankapp.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.bankapp.dbPassword | quote }}
