apiVersion: v1
kind: Secret
metadata:
  name: bankapp-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.bankapp.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.bankapp.dbPassword | quote }}
