apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bankapp-stage
  namespace: argocd
spec:
  project: bankapp-project
  source:
    repoURL: https://github.com/JiNaL1112/github-action-project.git
    targetRevision: stage
    path: bankapp
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: webapps-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true